name: Github CI
on: 
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.pull_request.title, 'wip') || github.event.pull_request.draft)"
    name: Create release build
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Install NPM packages
      run: |
        npm ci

    - name: Build with release configuration
      if: ${{ success() }}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: |
        dotnet build --configuration Release